export const COMPANIES_DICTIONARY = {
  APPLE: 'APPLE',
  GOOGLE: 'GOOGLE',
  WALMART: 'WALMART',
  EXXONMOBIL: 'EXXONMOBIL',
};

export const IDUSTRIES_DICTIONARY = {
  TECHNOLOGY: 'TECHNOLOGY',
  FINANCIALS: 'FINANCIALS',
  HEALTHCARE: 'HEALTHCARE'
};